[package]
name = "github_api"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version="0.12.19", features=["blocking", "json"] }
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.140"
